# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
BOX_NAME = "pygame-0.1.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = BOX_NAME

  config.vm.provision "shell", path: "provision.sh"
  
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = BOX_NAME 
    vbox.gui = true
    vbox.memory = 2048
  end
end
